[package]
name = "cargo-test"
version = "0.2.0"
authors = ["Joseph Hejderup <jhejderup@users.noreply.github.com>"]
repository = "https://github.com/jhejderup/cargo-test"

[dependencies]
semver = "0.6.0"